name: "Build"
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependencies
      run: |
        wget https://launchpadlibrarian.net/477095482/libhandy-0.0-dev_0.0.13-2_amd64.deb
        sudo apt install ./libhandy-0.0-dev_0.0.13-2_amd64.deb
        sudo apt-get update
        sudo apt-get install libcairo2-dev libpango1.0-dev libgtk-3-dev

    - name: Build
      run: go build -v .