name: "Build"
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependencies
      run: |
        sudo apt-get update
        echo "deb http://ftp.de.debian.org/debian sid main" | sudo tee -a /etc/apt/sources.list
        sudo apt-get install libcairo2-dev libpango1.0-dev libgtk-3-dev libhandy-0.0-0

    - name: Build
      run: go build -v .