name: "Build"
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependencies
      run: |
        sudo aptitude install debian-archive-keyring
        gpg --keyserver pgp.mit.edu --recv-keys 1F41B907
        gpg --armor --export 1F41B907 | apt-key add -
        echo "deb http://ftp.debian.org/debian stable main contrib non-free" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install libcairo2-dev libpango1.0-dev libgtk-3-dev libhandy-0.0-0

    - name: Build
      run: go build -v .